services:
  - type: web
    name: flask-app1
    env: docker
    repo: https://github.com/Aryan3572/SonicScribe
    dockerfilePath: ai-model/app1/Dockerfile
    plan: free
    region: singapore
    autoDeploy: true

  - type: web
    name: flask-app2
    env: docker
    repo: https://github.com/Aryan3572/SonicScribe
    dockerfilePath: ai-model/app2/Dockerfile
    plan: free
    region: singapore
    autoDeploy: true

  - type: web
    name: flask-app4
    env: docker
    repo: https://github.com/Aryan3572/SonicScribe
    dockerfilePath: ai-model/app4/Dockerfile
    plan: free
    region: singapore
    autoDeploy: true
